# Generated by Django 5.1.4 on 2024-12-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_remove_profile_address_auction_image_profile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auctions',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='viewer.auction'),
        ),
    ]
