# Generated by Django 5.1.4 on 2024-12-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_profile_is_premium_alter_watchlist_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prefer_communication',
            field=models.CharField(choices=[('mail', 'Post'), ('email', 'Email')], default='email', max_length=10),
        ),
    ]
