# Generated by Django 5.1.4 on 2024-12-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'permissions': [('auction_update', 'Can edit auction')]},
        ),
    ]
